biasharahub/biasharahub/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages.views import flatpage
from django.contrib.sitemaps.views import index, sitemap
from django.urls import path, include

from biasharahub.views import Home, NewsletterView
from business.sitemaps import BusinessSitemap
from reviews.sitemaps import ReviewSitemap

sitemaps = {
    'business': BusinessSitemap,
    'review': ReviewSitemap,

}
urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', Home.as_view(), name='home'),
                  path('newsletter', NewsletterView.as_view(), name='newsletter'),
                  path('accounts/', include('allauth.urls', )),
                  path('accounts/', include('accounts.urls', namespace='accounts')),
                  path('categories/', include('categories.urls', namespace='categories')),
                  path('business/', include('business.urls', namespace='business')),
                  path('reviews/', include('reviews.urls', namespace='reviews')),
                  path('comments/', include('comments.urls', namespace='comments')),
                  path('invitations/', include('invitations.urls', namespace='invitations')),
                  path('locations/', include('locations.urls', namespace='locations')),
                  path('opening-hours/', include('openinghours.urls', namespace='openinghours')),
                  path('about-us/', flatpage, {'url': '/about-us/'}, name='about'),
                  path('contact-us/', flatpage, {'url': '/contact-us/'}, name='contact'),
                  path('policy/', flatpage, {'url': '/policy/'}, name='policy'),

                  path('sitemap.xml', index, {'sitemaps': sitemaps}),
                  path('sitemap-<section>.xml', sitemap, {'sitemaps': sitemaps},
                       name='django.contrib.sitemaps.views.sitemap'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

biasharahub/reviews/urls.py
from django.urls import path

from favourites.views import vote_up, vote_down, ReviewVoteUp
from .views import ReviewList, ReviewDetail, ReviewCreate, ReviewEdit, photos

app_name = 'reviews'

urlpatterns = [
    path('', ReviewList.as_view(), name='list'),
    path('<slug:slug>/', ReviewDetail.as_view(), name='detail'),
    path('<slug:slug>/new/', ReviewCreate.as_view(), name='new'),
    path('<slug:slug>/edit/', ReviewEdit.as_view(), name='edit'),
    path('<slug:slug>/photos/', photos, name='photos'),
    path('<slug:slug>/review_like/', ReviewVoteUp.as_view(), name='review_like'),
    path('<slug:slug>/vote_up/', vote_up, name='vote_up'),
    path('<slug:slug>/vote_down/', vote_down, name='vote_down'),

]

biasharahub/reviews/models.py
from django.contrib.contenttypes.fields import GenericRelation, GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.urls import reverse
from django.utils.functional import cached_property
from django.utils.text import slugify

from accounts.models import User
from comments.models import Comment
from favourites.models import Vote
from hitcount.models import Hit
from utility.models import UrlMixin

RATING_CHOICES = (
    (1, '1'),
    (2, '2'),
    (3, '3'),
    (4, '4'),
    (5, '5'),
)


class Review(UrlMixin, models.Model):
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    content = models.TextField()

    publish = models.DateTimeField('date published', auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=200, blank=True, null=True)
    rating = models.IntegerField(choices=RATING_CHOICES, default=1)
    hit_count = GenericRelation(Hit)
    comments = GenericRelation(Comment)
    votes = GenericRelation(Vote, related_query_name='review')

    class Meta:
        unique_together = ('object_id', 'user')
        # unique_together = ('company', 'user')
        ordering = ['-publish']

    def save(self, *args, **kwargs):
        slug = slugify("%s at  %s" % (self.user, self.content_object))
        self.slug = slug
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('reviews:detail', kwargs={'slug': self.slug})

    def get_url_path(self):
        return reverse('reviews:detail', kwargs={'slug': self.slug})

    @cached_property
    def image_count(self):
        return self.photos.count()

    @cached_property
    def featured_image(self):
        return self.photos.all().first()


class ReviewImage(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE, related_name='photos')
    img = models.ImageField(upload_to='business/review_photos', null=True)
    alt = models.CharField(max_length=256, null=True, default="")

    def __str__(self):
        return self.img.url

biasharahub/reviews/forms.py
from builtins import super

from crispy_forms.bootstrap import InlineRadios
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Column, Row, Submit, Div
from django import forms
from django.forms import ModelForm, Textarea, RadioSelect, inlineformset_factory

from .models import Review, ReviewImage


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'content']
        widgets = {
            'rating': RadioSelect(),
            'content': Textarea(attrs={'cols': 40, 'rows': 5}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Div(
                    Div(
                        InlineRadios('rating', css_class='give_rating'),
                        css_class='br-wrapper br-theme-fontawesome-stars m-left-15'
                    ),
                    css_class='atbd_rating_stars',
                ),
            ),
            Row(
                Column('content', css_class='mt-10 form-group col-md-12 mb-0'),
                css_class='form-row', css_id='review_content'
            ),
            Submit('submit', 'Submit', css_class='btn btn-gradient btn-gradient-two')
        )


ReviewPhotoFormSet = inlineformset_factory(Review, ReviewImage, fields=('img', 'alt'),
                                             widgets={'img': forms.FileInput(attrs={
                                                 'class': 'form-control',
                                                 'placeholder': 'Upload photo Image'
                                             }),
                                                 'alt': forms.TextInput(attrs={
                                                     'class': 'form-control',
                                                     'placeholder': 'Describe image'
                                                 })},
                                             labels={'img': '',
                                                     'alt': ''},
                                             form=ReviewForm, extra=4)


class ReviewPhotoFormSetHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(ReviewPhotoFormSetHelper, self).__init__(*args, **kwargs)
        self.form_method = 'post'
        self.layout = Layout(
            Row(
                Column('img', css_class='mt-10 form-group col-md-5 mb-0'),
                Column('alt', css_class='mt-10 form-group col-md-7 mb-0'),
                css_class='form-row'
            ),
        )
        self.add_input(Submit("submit", "Save", css_class='btn btn-gradient'))

biasharahub/reviews/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView
from django.views.generic.detail import SingleObjectMixin

from accounts.decorators import UserRequiredMixin
from business.models import Business
from comments.forms import CommentForm
from hitcount.views import HitCountMixin
from reviews.forms import ReviewForm, ReviewPhotoFormSetHelper, ReviewPhotoFormSet
from .models import Review


class ReviewCreate(LoginRequiredMixin, CreateView):
    model = Review
    form_class = ReviewForm
    template_name = 'includes/form.html'

    def form_valid(self, form):
        form.instance.content_object = get_object_or_404(Business, slug=self.kwargs['slug'])
        form.instance.user = self.request.user
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, 'There was an error in this form')
        return self.render_to_response(self.get_context_data(form=form))

    def get_success_url(self):
        return reverse('business:detail', kwargs={'slug': self.object.content_object.slug})


@login_required
def photos(request, slug):
    """company = get_object_or_404(Business, slug=slug)"""
    review = Review.objects.get(slug=slug)
    form = ReviewPhotoFormSet(request.POST or None, request.FILES or None, instance=review)
    helper = ReviewPhotoFormSetHelper()

    if form.is_valid():
        form.save()
        messages.success(request, "Successfully Created")
    context = {
        "helper": helper,
        "form": form,
    }
    return render(request, "business/formset.html", context)


class ReviewEdit(LoginRequiredMixin,  UserRequiredMixin, UpdateView):
    model = Review
    form_class = ReviewForm
    template_name = 'includes/form.html'


class ReviewList(ListView):
    model = Review
    context_object_name = 'review'
    template_name = 'reviews/list.html'
    paginate_by = 10


class ReviewDetail(SingleObjectMixin, ListView):
    model = Review
    paginate_by = 10
    context_object_name = 'review'
    template_name = 'reviews/detail.html'
    count_hit = True

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Review.objects.all())
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm()


        return context

    def get_queryset(self):
        return self.object.comments.all()


class UserReviews(ListView):
    context_object_name = 'review'
    template_name = 'reviews/user_reviews.html'

    def get_queryset(self):
        user = self.request.user
        return Review.objects.filter(user=user).order_by('-publish')

biasharahub/templates/reviews/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load biasharahub %}

{% block title %}  {{ review.user }} | {{ block.super }} {% endblock %}

{% block bg-image-holder %}
<div class="bg_image_holder"><img alt="" src='{% static "img/breadcrumb1.jpg" %}'></div>
{% endblock %}

{% block page-title %}
<h1 class="page-title">{{ review.user }} </h1>
{% endblock %}

{% block breadcrumb_item %}
<li class="breadcrumb-item"><a href='{% url "reviews:list" %}'><i class="fa fa-list"></i>List</a></li>
<li aria-current="page" class="breadcrumb-item active">{{ review.user }}</li>
<li class="breadcrumb-item"><a href='{% url "reviews:edit" review.slug %}'><i class="fa fa-plus"></i>Edit</a></li>
{% endblock %}

{% block content %}


<section class="blog-area section-padding-strict border-bottom">
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <div class="post-details">
          <div class="post-head">
            <img alt="" src='{% if review.featured_image %}
                {{ review.featured_image }} {% else %} {% static "img/breadcrumb1.jpg" %}{% endif %}'>
          </div>
          <div class="post-content">
            <div class="post-header">
              <h3>{{ review.user }}</h3>
              <ul class="list-unstyled">
                <li>{{ review.publish|date }}</li>
                <li>By <a href="{{ review.user.get_absolute_url }}">{{ review.user }}</a></li>
                <li>In <a href="{{ review.content_object.get_absolute_url }}">{{ review.content_object.name }}</a></li>
                <li><a href="#">{{ review.comments.count }} Comment{{ review.comments.count|pluralize }}</a></li>
              </ul>
            </div>
            <div class="post-body">
              <p>{{ review.content }}</p>
            </div>
          </div>
        </div><!-- ends: .post-details -->
        <div class="post-bottom d-flex justify-content-between">
          <div class="action_button pull-left">
                    <a class=" btn btn-xs btn-secondary" href="{% url 'reviews:vote_up' slug=review.slug %}"></span>
                      Like |
                    <span>{{ review.votes.likes.count }}</span></a>
                    <a class=" btn btn-xs btn-danger" href="{% url 'reviews:vote_down' slug=review.slug %}"></span>
                      Dislike |
                    <span>{{ review.votes.dislikes.count }}</span></a>
                  </div>

          <div class="social-share d-flex align-items-center">
            <span class="m-right-15">Share Post: </span>
            <ul class="social-share list-unstyled">
              <li><a href=""><i class="fab fa-facebook-f"></i></a></li>
              <li><a href=""><i class="fab fa-twitter"></i></a></li>
              <li><a href=""><i class="fab fa-linkedin-in"></i></a></li>
              <li><a href=""><i class="fab fa-instagram"></i></a></li>
            </ul>
          </div>
        </div><!-- ends: .post-bottom -->
        <div class="post-author cardify border">
          <div class="author-thumb">
            <img alt="" class="rounded-circle" src="img/auth1.png">
          </div>
          <div class="author-info">
            <h5>About <span>{{ review.user.get_full_name  }}</span></h5>
            {% if review.user.bio %}
            <p>{{ review.user.bio }}</p>
            {% else %}
            <P>{{ review.user.get_full_name }} has decided to put a wall of heightened hysteria around them </P>
            {% endif %}
            <ul class="list-unstyled social-basic">
              <li><a href="{{ review.user.facebook }}"><i class="fab fa-facebook-f"></i></a></li>
              <li><a href="{{ review.user.twitter }}"><i class="fab fa-twitter"></i></a></li>
              <li><a href="{{ review.user.linkedin }}"><i class="fab fa-linkedin-in"></i></a></li>
              <li><a href="{{ review.user.instagram }}"><i class="fab fa-instagram"></i></a></li>
            </ul>
          </div>
        </div><!-- ends: .post-author -->
        <div class="comments-area m-top-60">
          <div class="comment-title">
            <h3>{{ review.comments.count }} Comment{{ review.comments.count|pluralize }}</h3>
          </div>
          <div class="comment-lists">
            <ul class="media-list list-unstyled">
              {% for comment in page_obj %}
              <li class="depth-1">
                <div class="media">
                  <div>
                    <a class="cmnt_avatar" href="{{ comment.user.get_absolute_url }}">
                      <img alt="" class="media-object rounded-circle" src="img/auth2.png">
                    </a>
                  </div>
                  <div class="media-body">
                    <div class="media_top">
                      <div class="heading_left">
                        <a href="{{ comment.user.get_absolute_url }}">
                          <h6 class="media-heading">{{ comment.user}}</h6>
                        </a>
                        <span>{{ comment.publish|date }}</span>
                      </div>
                      <a class="reply" href="#"><i class="la la-reply"></i> Reply</a>
                    </div>
                    <p>{{ comment.content }}</p>
                  </div>
                </div><!-- ends: .media -->
                <ul class="children list-unstyled">
                  <!-- Nested media object -->
                  {% for reply in comment.replies.all %}
                  <li class="depth-2">
                    <div class="media">
                      <div>
                        <a class="cmnt_avatar" href="#">
                          <img alt="Sample Image" class="media-object rounded-circle" src="img/auth3.png">
                        </a>
                      </div>
                      <div class="media-body">
                        <div class="media_top">
                          <div class="heading_left">
                            <a href="#">
                              <h6 class="media-heading">{{ reply.user }}</h6>
                            </a>
                            <span>{{ reply.publish|date }}</span>
                          </div>
                          <a class="reply" href="#"><i class="la la-reply"></i> Reply</a>
                        </div>
                        <p>{{ reply.content }}</p>
                      </div>
                    </div>
                  </li>
                  {% endfor %}
                </ul><!-- ends: .children -->
              </li><!-- ends: .depth-1 -->
              {% endfor %}
            </ul><!-- ends: .media-list -->
          </div><!-- ends: .comment-lists -->
          <div class="text-center m-top-50">
            {% include 'includes/pagination.html' %}
          </div>
        </div><!-- ends: .comment-area -->
        <div class="comment-form cardify m-top-60 margin-md-60 border">
          <div class="comment-title">
            <h3>Leave a Reply</h3>
            <span>Your email address will not be published. Required fields are marked <span
                class="color-primary">*</span></span>
          </div>
          <div class="comment_form_wrapper m-top-40">
            <form action="{% url 'comments:new' review.slug %}" class="form-ad" enctype="multipart/form-data"
                  method="post">
              <div class="form-group is-empty">
                {% csrf_token %}
                {% crispy form %}
              </div>
            </form>
          </div>
        </div><!-- ends: .comment-form -->
      </div><!-- ends: .col-lg-8 -->
      <div class="col-md-4 mt-5 mt-md-0">
        <div class="sidebar">
          <!-- search widget -->
          <div class="widget-wrapper">
            <div class="search-widget">
              <form action="#">
                <div class="input-group">
                  <input class="fc--rounded" placeholder="Search" type="text">
                  <button type="submit"><i class="la la-search"></i></button>
                </div>
              </form>
            </div>
          </div><!-- ends: .widget-wrapper -->
          <!-- category widget -->
          {% get_categories 5 %}
          <!-- ends: .widget-wrapper -->

          <!-- popular post -->
          {% get_popular_reviews %}
          <!-- ends: .widget-wrapper -->

          <!-- popular post -->
          {% get_popular_business %}
          <!-- ends: .widget-wrapper -->
          <!-- tags -->
          <!-- subscribe -->
          <div class="widget-wrapper">
            <div class="widget-default">
              <div class="widget-header">
                <h6 class="widget-title">Stay Updated</h6>
              </div>
              <div class="widget-content">
                <div class="subscribe-widget">
                  <form action="#">
                    <input class="form-control m-bottom-20" placeholder="Enter email" type="email">
                    <button class="btn btn-sm btn-primary shadow-none" type="submit">Subscribe</button>
                  </form>
                </div>
              </div>
            </div>
          </div><!-- ends: .widget-wrapper -->
          <!-- Social Connect -->
          <div class="widget-wrapper">
            <div class="widget-default">
              <div class="widget-header">
                <h6 class="widget-title">Connect &amp; Follow</h6>
              </div>
              <div class="widget-content">
                <div class="social social--small">
                  <ul class="d-flex flex-wrap">
                    <li><a class="facebook" href="#"><span class="fab fa-facebook-f"></span></a></li>
                    <li><a class="twitter" href="#"><span class="fab fa-twitter"></span></a></li>
                    <li><a class="linkedin" href="#"><span class="fab fa-linkedin-in"></span></a></li>
                    <li><a class="gplus" href="#"><span class="fab fa-google-plus-g"></span></a></li>
                  </ul>
                </div><!-- ends: .social -->
              </div>
            </div>
          </div><!-- ends: .widget-wrapper -->
        </div><!-- ends: .sidebar -->
      </div><!-- ends: .col-lg-4 -->
    </div>
  </div>
</section><!-- ends: .blog-area -->

{% endblock %}

biasharahub/templates/reviews/list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load biasharahub %}


{% block title %}  Review List  | {{ block.super }} {% endblock %}

{% block bg-image-holder %}
<div class="bg_image_holder"><img alt="" src='{% static "img/breadcrumb1.jpg" %}'></div>
{% endblock %}

{% block page-title %}
<h1 class="page-title">Review List</h1>
{% endblock %}

{% block breadcrumb_item %}
<li aria-current="page" class="breadcrumb-item active">All Listings</li>
{% endblock %}

{% block content %}

<section class="blog-area section-padding-strict border-bottom">
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <div class="blog-posts">
          {% for review in review %}
          <div class="blog-single">
            <div class="card post--card post--card2 ">
              {% if review.featured_image %}
              <figure>
                <a href="{{ review.get_absolute_url }}"><img alt="" src='
                {{ review.featured_image }}'></a>
                <figcaption>
                  <a href="{{ review.get_absolute_url }}"><i class="la la-image"></i></a>
                </figcaption>
              </figure>{% endif %}
              <div class="card-body">
                <h6><a href="{{ review.get_absolute_url }}">
                  {{ review.user.first_name }} reviewed {{ review.content_object.name }}
                </a></h6>
                <ul class="post-meta list-unstyled">
                  <li>{{ review.publish|date }} ( {{ review.publish|timesince }} ago )</li>
                  <li>by <a href="{{ review.user.get_absolute_url }}">{{ review.user }}</a></li>
                  <li>to <a href="{{ review.content_object.get_absolute_url }}">{{ review.content_object.name }}</a>
                  </li>
                  <li><a href="{{ review.get_absolute_url }}">{{ review.comments.count }}
                    Comment{{ review.comments.count|pluralize }}</a></li>
                </ul>
                <p>{{ review.content|truncatechars:254 }}</p>
              </div>
            </div><!-- End: .card -->
          </div><!-- ends: .blog-single -->
          {% endfor %}
        </div>
        <div class="m-top-50">
          <nav class="navigation pagination d-flex justify-content-center" role="navigation">
            {% include 'includes/pagination.html' %}
          </nav>
        </div>
      </div><!-- ends: .col-lg-8 -->
      <div class="col-md-4 mt-5 mt-md-0">
        <div class="sidebar">
          <!-- search widget -->
          <div class="widget-wrapper">
            <div class="search-widget">
              <form action="#">
                <div class="input-group">
                  <input class="fc--rounded" placeholder="Search" type="text">
                  <button type="submit"><i class="la la-search"></i></button>
                </div>
              </form>
            </div>
          </div><!-- ends: .widget-wrapper -->


          <!-- category widget -->
          {% get_categories 5 %}
          <!-- ends: .widget-wrapper -->

          <!-- popular post -->
          {% get_popular_reviews %}
          <!-- ends: .widget-wrapper -->

          <!-- popular post -->
          {% get_popular_business %}
          <!-- ends: .widget-wrapper -->


          <!-- subscribe -->
          <div class="widget-wrapper">
            <div class="widget-default">
              <div class="widget-header">
                <h6 class="widget-title">Stay Updated</h6>
              </div>
              <div class="widget-content">
                <div class="subscribe-widget">
                  <form action="#">
                    <input class="form-control m-bottom-20" placeholder="Enter email" type="email">
                    <button class="btn btn-sm btn-primary shadow-none" type="submit">Subscribe</button>
                  </form>
                </div>
              </div>
            </div>
          </div><!-- ends: .widget-wrapper -->
          <!-- Social Connect -->
          <div class="widget-wrapper">
            <div class="widget-default">
              <div class="widget-header">
                <h6 class="widget-title">Connect &amp; Follow</h6>
              </div>
              <div class="widget-content">
                <div class="social social--small">
                  <ul class="d-flex flex-wrap">
                    <li><a class="facebook" href="#"><span class="fab fa-facebook-f"></span></a></li>
                    <li><a class="twitter" href="#"><span class="fab fa-twitter"></span></a></li>
                    <li><a class="linkedin" href="#"><span class="fab fa-linkedin-in"></span></a></li>
                    <li><a class="gplus" href="#"><span class="fab fa-google-plus-g"></span></a></li>
                  </ul>
                </div><!-- ends: .social -->
              </div>
            </div>
          </div><!-- ends: .widget-wrapper -->
        </div><!-- ends: .sidebar -->
      </div><!-- ends: .col-lg-4 -->
    </div>
  </div>
</section><!-- ends: .blog-area -->
{% endblock %}