biasharahub/biasharahub/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages.views import flatpage
from django.contrib.sitemaps.views import index, sitemap
from django.urls import path, include

from biasharahub.views import Home, NewsletterView
from business.sitemaps import BusinessSitemap
from reviews.sitemaps import ReviewSitemap

sitemaps = {
    'business': BusinessSitemap,
    'review': ReviewSitemap,

}
urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', Home.as_view(), name='home'),
                  path('newsletter', NewsletterView.as_view(), name='newsletter'),
                  path('accounts/', include('allauth.urls', )),
                  path('accounts/', include('accounts.urls', namespace='accounts')),
                  path('categories/', include('categories.urls', namespace='categories')),
                  path('business/', include('business.urls', namespace='business')),
                  path('reviews/', include('reviews.urls', namespace='reviews')),
                  path('comments/', include('comments.urls', namespace='comments')),
                  path('invitations/', include('invitations.urls', namespace='invitations')),
                  path('locations/', include('locations.urls', namespace='locations')),
                  path('opening-hours/', include('openinghours.urls', namespace='openinghours')),
                  path('about-us/', flatpage, {'url': '/about-us/'}, name='about'),
                  path('contact-us/', flatpage, {'url': '/contact-us/'}, name='contact'),
                  path('policy/', flatpage, {'url': '/policy/'}, name='policy'),

                  path('sitemap.xml', index, {'sitemaps': sitemaps}),
                  path('sitemap-<section>.xml', sitemap, {'sitemaps': sitemaps},
                       name='django.contrib.sitemaps.views.sitemap'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

biasharahub/categories/urls.py
from django.urls import path

from .views import CategoryCreate, CategoryDetail, CategoryList, CategoryUpdate, CategoryBusinessCreate

app_name = 'categories'

urlpatterns = [
    path('new/', CategoryCreate.as_view(), name='new'),
    path('<slug:slug>/', CategoryDetail.as_view(), name='detail'),
    path('<slug:slug>/edit/', CategoryUpdate.as_view(), name='edit'),
    path('<slug:slug>/add_business/', CategoryBusinessCreate.as_view(), name='add_business'),

    path('', CategoryList.as_view(), name='list'),

]

biasharahub/reviews/urls.py
from django.urls import path

from favourites.views import vote_up, vote_down, ReviewVoteUp
from .views import ReviewList, ReviewDetail, ReviewCreate, ReviewEdit, photos

app_name = 'reviews'

urlpatterns = [
    path('', ReviewList.as_view(), name='list'),
    path('<slug:slug>/', ReviewDetail.as_view(), name='detail'),
    path('<slug:slug>/new/', ReviewCreate.as_view(), name='new'),
    path('<slug:slug>/edit/', ReviewEdit.as_view(), name='edit'),
    path('<slug:slug>/photos/', photos, name='photos'),
    path('<slug:slug>/review_like/', ReviewVoteUp.as_view(), name='review_like'),
    path('<slug:slug>/vote_up/', vote_up, name='vote_up'),
    path('<slug:slug>/vote_down/', vote_down, name='vote_down'),

]

biasharahub/categories/models.py
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse

from utility.models import Common


class Category(Common):
    icon = models.CharField(max_length=256, null=True, blank=True, default="")
    photo = models.ImageField(upload_to='category/photos', null=True, blank=True)


    class Meta:
        verbose_name_plural = "categories"

    def get_absolute_url(self):
        return reverse('categories:detail', kwargs={'slug': self.slug})

biasharahub/categories/forms.py
from builtins import super

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Column, Layout, Row, Submit
from crispy_forms.layout import Div
from django import forms
# from django.contrib.admin import widgets
from django.forms import ModelForm
from pagedown.widgets import PagedownWidget

from business.models import Business
from .models import Category


class CategoryForm(forms.ModelForm):
    name = forms.CharField(label='', required=True, widget=forms.TextInput(attrs={'placeholder': 'Category Name'}))
    icon = forms.CharField(label='', required=False, widget=forms.TextInput(attrs={'placeholder': 'Icon Class'}))
    photo = forms.ImageField(label='', required=False, widget=forms.ClearableFileInput(attrs={'placeholder': 'Photo'}))
    description = forms.CharField(label='', max_length=1024,
                                  widget=forms.Textarea(attrs={'placeholder': 'Description'}))

    class Meta:
        model = Category
        fields = ('name', 'icon', 'photo', 'description')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Column('name', css_class='mt-10 form-group col-md-6 mb-0'),
                Column('icon', css_class='mt-10 form-group col-md-6 mb-0'),
                css_class='form-group'
            ),
            Div(
                Div('photo', css_class='margin-top-10 upload-header btn btn-outline-secondary',
                    style='padding: 0;'),
                # style="background: white;",
                css_class='form-group text-center'
            ),
            Div('description', css_class='form-group'),
            Submit('submit', 'Submit'),

        )


class CategoryBusinessForm(ModelForm):
    logo = forms.ImageField(label='logo', required=False,
                            widget=forms.ClearableFileInput(attrs={'placeholder': 'Logo',
                                                                   'class': 'btn btn-outline-secondary'}))
    description = forms.CharField(widget=PagedownWidget())

    class Meta:
        model = Business
        fields = (
            'name', 'logo', 'email', 'description', 'website', 'location', 'address', 'services')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-8'
        self.helper.form_method = 'post'
        self.helper.layout = Layout(
            'name',
            'logo',
            'email',
            'description',
            'website',
            'location',
            'address',
            'services',
        )

biasharahub/categories/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView
from django.views.generic.detail import SingleObjectMixin

from business.forms import SocialProfileFormSet
from business.models import Business
from categories.forms import CategoryForm, CategoryBusinessForm
from categories.models import Category


class CategoryList(ListView):
    model = Category
    paginate_by = 12
    context_object_name = "category"
    template_name = 'categories/list.html'


class CategoryDetail(SingleObjectMixin, ListView):
    model = Category
    context_object_name = "category"
    template_name = 'categories/detail.html'
    paginate_by = 15

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Category.objects.all())
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        return self.object.company.all()


class CategoryCreate(LoginRequiredMixin, CreateView):
    model = Category
    form_class = CategoryForm
    template_name = 'includes/form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = " Add Category "
        return context


class CategoryUpdate(LoginRequiredMixin, UpdateView):
    model = Category
    form_class = CategoryForm
    template_name = 'includes/form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = " Update Category "
        return context


class CategoryBusinessCreate(LoginRequiredMixin, CreateView):
    model = Business
    form_class = CategoryBusinessForm
    template_name = 'business/form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['social_form'] = SocialProfileFormSet(self.request.POST)

        else:
            context['social_form'] = SocialProfileFormSet()

        return context

    def form_valid(self, form):
        form.instance.category = get_object_or_404(Category, slug=self.kwargs['slug'])
        form.instance.user = self.request.user
        form.save()

        context = self.get_context_data(form=form)
        social_form = context['social_form']

        if social_form.is_valid():
            response = super().form_valid(form)
            social_form.instance = self.object
            social_form.save()
            return response
        else:
            return super().form_invalid(form)

    def form_invalid(self, form):
        """
        If the form is invalid, re-render the context data with the
        data-filled form and errors.
        """
        print('the is an error in your form')
        messages.warning(self.request, 'There was an error in this form')
        return self.render_to_response(self.get_context_data(form=form))

    def get_success_url(self):
        return reverse('business:detail', kwargs={'slug': self.object.slug})

biasharahub/templates/categories/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}  {{ category.name }}  | {{ block.super }} {% endblock %}

{% block bg-image-holder %}
<div class="bg_image_holder"><img alt="" src='{% static "img/breadcrumb1.jpg" %}'></div>
{% endblock %}

{% block page-title %}
<h1 class="page-title">{{ category.name }}</h1>
{% endblock %}

{% block breadcrumb_item %}
<li class="breadcrumb-item"><a href='{% url "categories:list" %}'><i class="fa fa-plus"></i>list</a></li>
<li aria-current="page" class="breadcrumb-item active">{{ category.name }}</li>
<li class="breadcrumb-item"><a href='{% url "categories:edit" category.slug %}'><i class="fa fa-plus"></i>Edit</a></li>
{% endblock %}


{% block content %}
<section class="author-info-area section-padding-strict section-bg">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-md-7 m-bottom-30">
        <div class="atbd_author_module">
          <div class="atbd_content_module">
            <div class="atbd_content_module__tittle_area">
              <div class="atbd_area_title">
                <h4><span class="fa fa-location"></span>{{ category.name }}</h4>
              </div>
            </div>
            <div class="atbdb_content_module_contents">
              <p>{{ category.description }}</p>
            </div>
                      <div class="atbd_listing_bottom_content">
             <a class="btn btn-primary" href="{% url 'categories:add_business' slug=category.slug %}">
              <span class="la la-plus"></span>Add Here</a>
          </div>
          </div>
        </div><!-- ends: .atbd_author_module -->
      </div><!-- ends: .col-md-8 -->
      <div class="col-lg-12">
        <div class="row">
          {% for business in page_obj %}
          <div class="col-lg-4 col-sm-6">
            <div class="atbd_single_listing ">
              <article class="atbd_single_listing_wrapper">
                <figure class="atbd_listing_thumbnail_area">
                  <div class="atbd_listing_image">
                    <a href="">
                      <img alt="listing image" src="img/p1.jpg">
                    </a>
                  </div><!-- ends: .atbd_listing_image -->
                  <div class="atbd_author atbd_author--thumb">
                    <a href="{{ business.get_absolute_url }}">
                      <img alt="Logo" class="center-cropped" src='{% if business.logo %}
                          {{ business.logo3.url }} {% else %} {% static "img/author-thumb2.jpg" %} {% endif %}'>
                      <span class="custom-tooltip">{{ business.name }}</span>
                    </a>
                  </div>
                  <div class="atbd_thumbnail_overlay_content">
                    <ul class="atbd_upper_badge">
                      {% if business.featured %}
                      <li><span class="atbd_badge atbd_badge_featured">Featured</span></li>
                      {% endif %}
                      {% if business.verified %}
                      <li><span class="atbd_badge atbd_badge_popular">Verified</span></li>
                      {% endif %}
                    </ul><!-- ends .atbd_upper_badge -->
                  </div><!-- ends: .atbd_thumbnail_overlay_content -->
                </figure><!-- ends: .atbd_listing_thumbnail_area -->
                <div class="atbd_listing_info">
                  <div class="atbd_content_upper">
                    <h4 class="atbd_listing_title">
                      <a href="">{{ business.name }}</a>
                    </h4>
                    <div class="atbd_listing_meta">
                      <span class="atbd_meta atbd_listing_rating">{{ business.average_rating | floatformat }}
                        <i class="la la-star"></i></span>
                      <span class="atbd_meta atbd_listing_price">$55.00</span>
                      <span class="atbd_meta atbd_badge_open">Open Now</span>
                    </div><!-- End atbd listing meta -->
                    <div class="atbd_listing_data_list">
                      <ul>
                        <li>
                          <p><span class="la la-map-marker"></span>{{ business.address }},
                            {{ business.location }}, {{ business.location.country }}</p>
                        </li>
                        <li>
                          <p><span class="la la-phone"></span>(+254) {{ business.phone }}</p>
                        </li>
                        <li>
                          <p><span class="la la-calendar-check-o"></span>
                            Posted {{ business.publish|timesince }} ago</p>
                        </li>
                      </ul>
                    </div><!-- End atbd listing meta -->
                  </div><!-- end .atbd_content_upper -->
                  <div class="atbd_listing_bottom_content">
                    <div class="atbd_content_left">
                      <div class="atbd_listing_category">
                        <a href=""><span class="la la-glass"></span>{{ business.category }}</a>
                      </div>
                    </div>
                    <ul class="atbd_content_right">
                      <li class="atbd_count"><span class="la la-eye"></span>900+</li>
                      <li class="atbd_save">
                        <span class="la la-heart-o"></span>
                      </li>
                    </ul>
                  </div><!-- end .atbd_listing_bottom_content -->
                </div><!-- ends: .atbd_listing_info -->
              </article><!-- atbd_single_listing_wrapper -->
            </div>
          </div><!-- ends: .col-md-6 -->
          {% endfor %}
        </div>
        {% include 'includes/pagination.html' %}
      </div><!-- ends: .col-lg-12 -->
    </div>
  </div>
</section><!-- ends: .author-info-area -->
{% endblock content %}

biasharahub/templates/categories/list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}  Categories  | {{ block.super }} {% endblock %}

{% block stylesheet %}
<style>
      .category--img4 {
        height: 280px;
      }
      img {
        width: 100%;
        height: 100%;
        object-fit: cover;
      }

</style>
{% endblock %}

{% block bg-image-holder %}
<div class="bg_image_holder"><img alt="" src='{% static "img/breadcrumb1.jpg" %}'></div>
{% endblock %}


{% block page-title %}
<h1 class="page-title">Categories</h1>
{% endblock %}

{% block breadcrumb_item %}
<li class="breadcrumb-item"><a href='{% url "categories:new" %}'><i class="fa fa-plus"></i>New</a></li>
<li aria-current="page" class="breadcrumb-item active">All Categories</li>
{% endblock %}

{% block content %}

<section class="section-padding-1_7 border-bottom">
  <div class="container">
    <div class="row">
      {% for category in category %}
      <div class="col-lg-4 col-sm-6">
        <div class="category-single category--img">
          <figure class="category--img4">
            <img src='{% if category.photo %} {{ category.photo.url }} {% else %} {% static "img/cat1.jpg" %} {% endif %}' alt="">
            <figcaption class="overlay-bg">
              <a href="{{ category.get_absolute_url }}" class="cat-box">
                <div>
                  <div class="icon">
                    <span class="{{ category.icon }}"></span>
                  </div>
                  <h4 class="cat-name">{{ category.name }}</h4>
                  <span class="badge badge-pill badge-success">{{ category.business_set.count }}
                                          Listing{{ category.business_set.count }}</span>
                </div>
              </a>
            </figcaption>
          </figure>
        </div><!-- ends: .category-single -->
      </div><!-- ends: .col -->
      {% endfor %}
    </div>
  </div>
</section><!-- ends: section -->
{% endblock %}