biasharahub/accounts/urls.py
from django.urls import path

from .views import Dashboard, Detail, UserUpdateView

app_name = 'accounts'

urlpatterns = [
    # path('signup/', SignUp.as_view(), name='signup'),
    # path('activate/<str:uid>/<str:token>', Activate.as_view(), name='activate'),
    #
    # path('signup1/', SignUpView.as_view(), name='register'),
    # path('login/', UserLogin.as_view(), name='login'),
    path('dashboard/', Dashboard.as_view(), name='dashboard'),
    path('<pk>/', Detail.as_view(), name='detail'),
    # path('<pk>/logout/', UserLogout.as_view(), name='logout'),
    # path('reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html',
    #                                                     email_template_name='accounts/password_reset_email.html',
    #                                                     subject_template_name='accounts/password_reset_subject.txt'),
    #      name='password_reset'),
    # path('reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
    #      name='password_reset_done'),
    # path('reset/<uidb64>/<token>/',
    #      auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
    #      name='password_reset_confirm'),
    # path('reset/complete/',
    #      auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
    #      name='password_reset_complete'),
    path('settings/account_edit/', UserUpdateView.as_view(), name='account_edit'),
    # path('settings/password/', auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html',
    #                                                                  success_url=reverse_lazy(
    #                                                                      'accounts:password_change_done')),
    #      name='password_change'),
    # path('settings/password/done/',
    #      auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'),
    #      name='password_change_done'),
]

biasharahub/biasharahub/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages.views import flatpage
from django.contrib.sitemaps.views import index, sitemap
from django.urls import path, include

from biasharahub.views import Home, NewsletterView
from business.sitemaps import BusinessSitemap
from reviews.sitemaps import ReviewSitemap

sitemaps = {
    'business': BusinessSitemap,
    'review': ReviewSitemap,

}
urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', Home.as_view(), name='home'),
                  path('newsletter', NewsletterView.as_view(), name='newsletter'),
                  path('accounts/', include('allauth.urls', )),
                  path('accounts/', include('accounts.urls', namespace='accounts')),
                  path('categories/', include('categories.urls', namespace='categories')),
                  path('business/', include('business.urls', namespace='business')),
                  path('reviews/', include('reviews.urls', namespace='reviews')),
                  path('comments/', include('comments.urls', namespace='comments')),
                  path('invitations/', include('invitations.urls', namespace='invitations')),
                  path('locations/', include('locations.urls', namespace='locations')),
                  path('opening-hours/', include('openinghours.urls', namespace='openinghours')),
                  path('about-us/', flatpage, {'url': '/about-us/'}, name='about'),
                  path('contact-us/', flatpage, {'url': '/contact-us/'}, name='contact'),
                  path('policy/', flatpage, {'url': '/policy/'}, name='policy'),

                  path('sitemap.xml', index, {'sitemaps': sitemaps}),
                  path('sitemap-<section>.xml', sitemap, {'sitemaps': sitemaps},
                       name='django.contrib.sitemaps.views.sitemap'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

biasharahub/categories/urls.py
from django.urls import path

from .views import CategoryCreate, CategoryDetail, CategoryList, CategoryUpdate, CategoryBusinessCreate

app_name = 'categories'

urlpatterns = [
    path('new/', CategoryCreate.as_view(), name='new'),
    path('<slug:slug>/', CategoryDetail.as_view(), name='detail'),
    path('<slug:slug>/edit/', CategoryUpdate.as_view(), name='edit'),
    path('<slug:slug>/add_business/', CategoryBusinessCreate.as_view(), name='add_business'),

    path('', CategoryList.as_view(), name='list'),

]

biasharahub/reviews/urls.py
from django.urls import path

from favourites.views import vote_up, vote_down, ReviewVoteUp
from .views import ReviewList, ReviewDetail, ReviewCreate, ReviewEdit, photos

app_name = 'reviews'

urlpatterns = [
    path('', ReviewList.as_view(), name='list'),
    path('<slug:slug>/', ReviewDetail.as_view(), name='detail'),
    path('<slug:slug>/new/', ReviewCreate.as_view(), name='new'),
    path('<slug:slug>/edit/', ReviewEdit.as_view(), name='edit'),
    path('<slug:slug>/photos/', photos, name='photos'),
    path('<slug:slug>/review_like/', ReviewVoteUp.as_view(), name='review_like'),
    path('<slug:slug>/vote_up/', vote_up, name='vote_up'),
    path('<slug:slug>/vote_down/', vote_down, name='vote_down'),

]

biasharahub/templates/includes/breadcrumb.html
<section class="header-breadcrumb bgimage overlay overlay--dark">
  {% block bg-image-holder %}
  <div class="bg_image_holder"><img alt="" src="img/breadcrumb1.jpg"></div>
  {% endblock %}
  <!--      mainmenu wrapper-->
  {% include 'includes/menu.html' %}
  <!-- ends: .mainmenu-wrapper -->
  <div class="breadcrumb-wrapper content_above">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          {% block page-title %}
          {% endblock %}
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href='{% url "home" %}'><i class="fa fa-home"></i>Home</a></li>
              {% block breadcrumb_item %}
              <li aria-current="page" class="breadcrumb-item active">All Listings</li>
              {% endblock %}
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </div><!-- ends: .breadcrumb-wrapper -->
</section>

      <div class="row">


        <div class="col-lg-4 col-md-5 d-flex align-items-end justify-content-start justify-content-md-end">
          <div class="atbd_listing_action_area">
            <div class="atbd_action atbd_save">
              <div class="action_button">
                <a class="atbdp-favourites" href=""><span class="la la-heart-o"></span> Save</a>
              </div>
            </div>
            <div class="atbd_action atbd_share dropdown">
                                <span aria-expanded="false" aria-haspopup="true" class="dropdown-toggle"
                                      data-toggle="dropdown" id="social-links" role="menu">
                                    <span class="la la-share"></span>Share
                                </span>
              <div aria-labelledby="social-links" class="atbd_director_social_wrap dropdown-menu">
                <ul class="list-unstyled">
                  <li>
                    <a href="" target="_blank"><span
                        class="fab fa-facebook-f color-facebook"></span>Facebook</a>
                  </li>
                  <li>
                    <a href="" target="_blank"><span class="fab fa-twitter color-twitter"></span>Twitter</a>
                  </li>
                  <li>
                    <a href="" target="_blank"><span
                        class="fab fa-pinterest-p color-pinterest"></span>Pinterest</a>
                  </li>
                  <li>
                    <a href="" target="_blank"><span
                        class="fab fa-google-plus-g color-gplus"></span>Google Plus</a>
                  </li>
                  <li>
                    <a href="" target="_blank"><span
                        class="fab fa-linkedin-in color-linkedin"></span>LinkedIn</a>
                  </li>
                  <li>
                    <a href="" target="_blank"><span class="fab fa-tumblr color-tumblr"></span>Tumblr</a>
                  </li>
                  <li>
                    <a href="" target="_blank"><span class="fab fa-vk color-vk"></span>VKontakte</a>
                  </li>
                </ul>
              </div>
              <!--Ends social share-->
            </div>
            <!-- Report Abuse-->
            <div class="atbd_action atbd_report">
              <div class="action_button">
                <a data-target="#atbdp-report-abuse-modal" data-toggle="modal" href=""><span
                    class="la la-flag-o"></span> Report</a>
              </div>
              <!-- Modal (report abuse form) -->
            </div>
          </div><!-- ends: .atbd_listing_action_area -->
        </div>
      </div>
    </div>
    <div aria-hidden="true" aria-labelledby="atbdp-report-abuse-modal-label" class="modal fade"
         id="atbdp-report-abuse-modal" role="dialog"
         tabindex="-1">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <form action="/" class="form-vertical" id="atbdp-report-abuse-form">
            <div class="modal-header">
              <h3 class="modal-title" id="atbdp-report-abuse-modal-label">Report Abuse</h3>
              <button class="close" data-dismiss="modal" type="button"><span aria-hidden="true">×</span>
              </button>
            </div>
            <div class="modal-body">
              <div class="form-group">
                <label class="not_empty" for="atbdp-report-abuse-message">Your Complaint<span
                    class="atbdp-star">*</span></label>
                <textarea class="form-control" id="atbdp-report-abuse-message" placeholder="Message..."
                          required="" rows="4"></textarea>
              </div>
            </div>
            <div class="modal-footer">
              <button class="btn btn-danger btn-sm" data-dismiss="modal" type="button">Close</button>
              <button class="btn btn-secondary btn-sm" type="submit">Submit</button>
            </div>
          </form>
        </div>
      </div>
    </div>
    <div aria-hidden="true" aria-labelledby="claim_listing_label" class="modal fade" id="moda_claim_listing"
         role="dialog" tabindex="-1">
      <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="claim_listing_label"><i class="la la-check-square"></i> Claim This
              Business</h5>
            <button aria-label="Close" class="close" data-dismiss="modal" type="button">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <form action="/">
              <div class="form-group">
                <div class="row">
                  <div class="col-md-6">
                    <input class="form-control" placeholder="Your Name" required type="text">
                  </div>
                  <div class="col-md-6">
                    <input class="form-control" placeholder="Email Address" required type="email">
                  </div>
                </div>
              </div>
              <div class="form-group">
                <div class="row">
                  <div class="col-md-6">
                    <input class="form-control" placeholder="Phone Number" required type="text">
                  </div>
                  <div class="col-md-6">
                    <input class="form-control" placeholder="Listing URL" required type="url">
                  </div>
                </div>
              </div>
              <div class="form-group">
                <div class="row">
                  <div class="col-lg-12">
                                        <textarea class="form-control" placeholder="Provie Listing Information" required
                                                  rows="6"></textarea>
                    <button class="btn btn-secondary" type="submit">Submit Query</button>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div><!-- ends: .listing-info -->
</section><!-- ends: .card-details-wrapper -->

biasharahub/templates/includes/call-to-action.html
<!--call to action-->
      <div class="header-style-2">
        <div class="container">
          <div class="row">
            <div class="col-xs-12 col-sm-6">
              <div class="hero-content-v2">
                <h3>Add Reviews or even your resume and let business owners find you </h3>
                <p>
                </p>
                <a href="#" class="page-scroll btn btn-lg btn-default-filled">Sign Up</a>
              </div>
            </div>
            <div class="col-xs-12 col-sm-6">
              <figure>
                <img src="static/img/bg/hero-2.png" alt="">
              </figure>
            </div>

          </div>
        </div>
      </div>
<!--end of call to action-->

biasharahub/templates/includes/cat_to_add_biz.html
{% block content %}

<div aria-hidden="true" aria-labelledby="category_modal_label" class="modal fade" id="category_modal" role="dialog"
     tabindex="-1">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <h5 class="modal-title"><i class="la la-lock"></i> Select category to add your business</h5>
        <button aria-label="Close" class="close" type="button">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body atbd_location_grid_wrap">
        <div class="container">
          <div class="row">
            {% for category in categories %}
            <div class="col-lg-3">
              <a class="atbd_location_grid" href="{% url 'categories:add_business' slug=category.slug %}">{{ category.name }}</a>
            </div><!-- ends: .col-lg-3 -->
            {% endfor %}
            <div class="col-lg-3 col-md-4 col-sm-6">
              <a class="atbd_location_grid" href='{% url "business:new" %}'>None</a>
            </div><!-- ends: .col-lg-3 -->
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

biasharahub/templates/includes/footer.html
{% load biasharahub %}
<footer class="footer-three footer-grey p-top-95">
  <div class="footer-top p-bottom-25">
    <div class="container">
      <div class="row">
        <div class="col-lg-2 col-sm-6">
          <div class="widget widget_pages">
            <h2 class="widget-title">Company Info</h2>
            <ul class="list-unstyled">
              <li class="page-item"><a href="{% url 'about' %}">About Us</a></li>
              <li class="page-item"><a href="{% url 'contact' %}">Conact Us</a></li>
              <li class="page-item"><a href="{% url 'business:list' %}">Biasharas</a></li>
              <li class="page-item"><a href="{% url 'policy' %}">Privacy Policy</a></li>
            </ul>
          </div>
        </div><!-- ends: .col-lg-3 -->
        <div class="col-lg-3 d-flex justify-content-lg-center  col-sm-6">
          <div class="widget widget_pages">
            <h2 class="widget-title">Helpful Links</h2>
            <ul class="list-unstyled">
              <li class="page-item"><a href="{% url 'account_signup' %}">Join BiasharaHub</a></li>
              <li class="page-item"><a href="{% url 'account_login' %}">Login</a></li>
              <li class="page-item"><a href="{% url 'about' %}">How it Work</a></li>
              <li class="page-item"><a href="{% url 'reviews:list' %}">Reviews</a></li>
              <li class="page-item"><a href="{% url 'locations:list' %}">Locations</a></li>
              <li class="page-item"><a href="{% url 'categories:list' %}">Categories</a></li>
            </ul>
          </div>
        </div><!-- ends: .col-lg-3 -->
        <div class="col-lg-3 col-sm-6">
          <div class="widget widget_social">
            <h2 class="widget-title">Connect with Us</h2>
            <ul class="list-unstyled social-list">
              <li><a href=""><span class="mail"><i class="la la-envelope"></i></span> Contact Support</a></li>
              <li><a href=""><span class="twitter"><i class="fab fa-twitter"></i></span> Twitter</a></li>
              <li><a href=""><span class="facebook"><i class="fab fa-facebook-f"></i></span> Facebook</a></li>
              <li><a href=""><span class="instagram"><i class="fab fa-instagram"></i></span> Instagram</a></li>
              <li><a href=""><span class="gplus"><i class="fab fa-google-plus-g"></i></span> Google+</a></li>
            </ul>
          </div><!-- ends: .widget -->
        </div><!-- ends: .col-lg-3 -->
        <div class="col-lg-4 col-sm-6">
          <div class="widget widget_text">
            <h2 class="widget-title">Subscribe to Newsletter</h2>
            {% comment %}
            <div class="textwidget">
              <p>At these time this is not working.</p>
              <ul class="list-unstyled store-btns">
                <li><a class="btn btn-dark btn-md btn-icon btn-icon" href=""><span class="fa fa-mailchimp">
                                  </span> Subscribe </a></li>
              </ul>
            </div>
            {% endcomment %}

          </div><!-- ends: .widget -->
        </div><!-- ends: .col-lg-3 -->
      </div>
    </div>
  </div><!-- ends: .footer-top -->
  <div class="footer-bottom">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="footer-bottom--content">
            <a class="footer-logo" href=""><img alt="" src="static/img/logo.png"></a>
            <p class="m-0 copy-text">©2020 BiasharaHub</p>
            <ul class="list-unstyled lng-list">
              <li><a href="">English</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div><!-- ends: .footer-bottom -->
</footer><!-- ends: .footer -->

          {% get_cat_to_add_biz %}
          {% get_login %}
          {% get_signup %}

biasharahub/templates/includes/form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}  Form  | {{ block.super }} {% endblock %}

{% block bg-image-holder %}
<div class="bg_image_holder"><img alt="" src='{% static "img/breadcrumb1.jpg" %}'></div>
{% endblock %}

{% block page-title %}
<h1 class="page-title">Form</h1>
{% endblock %}

{% block breadcrumb_item %}
<li aria-current="page" class="breadcrumb-item active">Form</li>
{% endblock %}

{% block content %}


<div class="col-lg-10 offset-lg-1">
    <div class="atbd_content_module">
        <div class="atbd_content_module__tittle_area">
            <div class="atbd_area_title">
                <h4><span class="la la-calendar-check-o"></span> Form</h4>
            </div>
        </div>
        <div class="atbdb_content_module_contents">
            <div id="faqs_info_sortable_container" class="ui-sortable">

                    <form enctype="multipart/form-data" class="form-ad" action="." method="POST">
                        <div class="form-group is-empty">
                            {% csrf_token %}
                            {% crispy form %}
                        </div>
                    </form>

            </div>
        </div><!-- ends: .atbdb_content_module_contents -->
    </div><!-- ends: .atbd_content_module -->
</div><!-- ends: .col-lg-10 -->


{% endblock content %}

biasharahub/templates/includes/header.html
<div class="header-style-3">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6">
        <figure>
          <img alt="" src="static/img/bg/business-woman.png">
          <!--<img src="static/img/bg/hero-2.png" alt="">-->
        </figure>
      </div>
      <div class="col-xs-12 col-sm-6">
        <div class="hero-content-v2">
          <h3 class="slide-title animated fadeInDown"><strong>Add your Business and see the lot's of
            possibilities</strong></h3>
          <p>
            sign up, add company, help people to know you better!
          </p>
          <a class="btn btn-lg btn-border animated fadeInUp" href="{% url 'accounts:employer_signup' %}">
            Business Sign Up
          </a>
          <a class="btn btn-lg btn-success animated fadeInUp" href="{% url 'accounts:normal_user_signup' %}">
            Normal Sign Up
          </a>

        </div>
      </div>
    </div>
  </div>
</div>

biasharahub/templates/includes/menu.html
{% load staticfiles %}
<!--mainmenu wrapper-->
<div class="mainmenu-wrapper">
  <div class="menu-area menu1 menu--light">
    <div class="top-menu-area">
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-12">
            <div class="menu-fullwidth">
              <div class="logo-wrapper order-lg-0 order-sm-1">
                <div class="logo logo-top">
                  <a href='{% url "home" %}'><img alt="logo image" class="img-fluid"
                                                  src='{% static "img/logo-white.png" %}'></a>
                </div>
              </div><!-- ends: .logo-wrapper -->
              <div class="menu-container order-lg-1 order-sm-0">
                <div class="d_menu">
                  <nav class="navbar navbar-expand-lg mainmenu__menu">
                    <button aria-controls="direo-navbar-collapse" aria-expanded="false" aria-label="Toggle navigation"
                            class="navbar-toggler" data-target="#direo-navbar-collapse"
                            data-toggle="collapse" type="button">
                      <span class="navbar-toggler-icon icon-menu"><i class="la la-reorder"></i></span>
                    </button>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="direo-navbar-collapse">
                      <ul class="navbar-nav">
                        <li>
                          <a href='{% url "home" %}'>Home</a>
                        </li>
                        <li class="dropdown has_dropdown">
                          <a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown"
                             href="#"
                             id="drop3" role="button">Biashara</a>
                          <ul aria-labelledby="drop3" class="dropdown-menu">
                            <li><a href='{% url "business:list" %}'>Biasharas</a></li>
                            <li><a href='{% url "business:new" %}'>Add Biashara</a></li>
                          </ul>
                        </li>
                        <li class="dropdown has_dropdown">
                          <a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown"
                             href="#"
                             id="drop4" role="button">Categories</a>
                          <ul aria-labelledby="drop4" class="dropdown-menu">
                            <li><a href='{% url "categories:list" %}'>All Categories</a></li>
                            <li><a href='{% url "locations:list" %}'>All Locations</a></li>
                          </ul>
                        </li>
                        <li class="dropdown has_dropdown">
                          <a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown"
                             href="#"
                             id="drop2" role="button">
                            Reviews
                          </a>
                          <ul aria-labelledby="drop2" class="dropdown-menu">
                            <li><a href='{% url "reviews:list" %}'>Reviews</a></li>
                            <li><a href='{% url "reviews:list" %}'>Add Reviews</a></li>
                          </ul>
                        </li>
                      </ul>
                    </div>
                    <!-- /.navbar-collapse -->
                  </nav>
                </div>
              </div>
              <div class="menu-right order-lg-2 order-sm-2">
                <div class="search-wrapper">
                  <div class="nav_right_module search_module">
                    <span class="icon-left" id="basic-addon9"><i class="la la-search"></i></span>
                    <div class="search_area">
                      <form action="/">
                        <div class="input-group input-group-light">
                          <input autocomplete="off" class="form-control search_field top-search-field"
                                 placeholder="What are you looking for?" type="text">
                        </div>
                      </form>
                    </div>
                  </div>
                </div><!-- ends: .search-wrapper -->


                <!-- start .author-area -->
                <div class="author-area">
                  <div class="author__access_area">
                    <ul class="d-flex list-unstyled align-items-center">
                      <li>
                        <a class="btn btn-xs btn-gradient btn-gradient-two"
                           data-target="#category_modal" data-toggle="modal"
                           href='{% url "business:new" %}'>
                          <span class="la la-plus"></span> Add Biashara
                        </a>
                      </li>
                      {% if not request.user.is_authenticated %}
                      <li>
                        <a class="access-link" data-target="#login_modal" data-toggle="modal"
                           href='{% url "account_login" %}'><i class="fa fa-lock"></i> Login</a>
                        <span>or</span>
                        <a class="access-link" data-target="#signup_modal" data-toggle="modal"
                           href="{% url 'account_signup' %}"><i class="fa fa-pencil"></i> Register</a>
                      </li>
                    </ul>
                    {% else %}


                    <nav class="navbar navbar-expand-lg mainmenu__menu">
                      <div class="collapse navbar-collapse" id="direo-navbar-collapse">
                        <ul class="navbar-nav">
                          <li class="dropdown has_dropdown">
                            <a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown"
                               href="#"
                               id="drop5" role="button"><i class="la la-user"></i>
                              Welcome {{ request.user.get_short_name }}
                            </a>
                            <ul aria-labelledby="drop4" class="dropdown-menu">
                              <li><a href="{% url 'accounts:dashboard' %}">Dashboard</a></li>
                              <li><a href="{% url 'accounts:detail' request.user.pk %}">My Profile</a></li>
                              <li><a href="{% url 'account_reset_password' %}">Change Password</a></li>
                              <li><a href="{% url 'accounts:account_edit' %}">Edit Profile</a></li>
                              <li><a href="{% url 'account_logout' %}">Logout</a></li>
                            </ul>
                          </li>
                        </ul>
                      </div>
                    </nav>

                    {% endif %}
                  </div>
                </div>
                <!-- end .author-area -->


              </div><!-- ends: .menu-right -->
            </div>
          </div>
        </div>
        <!-- end /.row -->
      </div>
      <!-- end /.container -->
    </div>
    <!-- end  -->
  </div>
</div>
<!-- ends: .mainmenu-wrapper -->

biasharahub/templates/includes/messages_display.html
 {% if messages %}
    <div class='messages'>

    <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
    {% endfor %}
    </ul>

    </div>
{% endif %}

biasharahub/templates/includes/newsletter.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}  Form  | {{ block.super }} {% endblock %}

{% block bg-image-holder %}
<div class="bg_image_holder"><img alt="" src='{% static "img/breadcrumb1.jpg" %}'></div>
{% endblock %}

{% block page-title %}
<h1 class="page-title">Form</h1>
{% endblock %}

{% block breadcrumb_item %}
<li aria-current="page" class="breadcrumb-item active">Form</li>
{% endblock %}

{% block content %}


<div class="col-lg-10 offset-lg-1">
    <div class="atbd_content_module">
        <div class="atbd_content_module__tittle_area">
            <div class="atbd_area_title">
                <h4><span class="la la-calendar-check-o"></span> Subscribe to our Newsletter</h4>
            </div>
        </div>
        <div class="atbdb_content_module_contents">
            <div id="faqs_info_sortable_container" class="ui-sortable">

                    <form enctype="multipart/form-data" class="form-ad" action="." method="POST">
                        <div class="form-group is-empty">
                            {% csrf_token %}
                            {% crispy subscribe_form %}
                        </div>
                    </form>

            </div>
        </div><!-- ends: .atbdb_content_module_contents -->
    </div><!-- ends: .atbd_content_module -->
</div><!-- ends: .col-lg-10 -->


{% endblock content %}

biasharahub/templates/includes/pagination.html
{% if is_paginated %}
<div class="row">
  <div class="col-lg-12">
    <nav class="navigation pagination d-flex justify-content-end" role="navigation">
      <div class="nav-links">
        {% if page_obj.has_previous %}
        <a class="prev page-numbers" href="?page={{ page_obj.previous_page_number }}">
          <span class="la la-long-arrow-left"></span></a>
        {% else %}
        <a class="prev page-numbers disabled"><span class="la la-long-arrow-left"></span></a>
        {% endif %}
        {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
        <span aria-current="page" class="page-numbers current">{{ i }}</span>
        {% else %}

        <a class="page-numbers" href="?page={{ i }}">{{ i }}</a>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <a class="next page-numbers" href="?page={{ page_obj.next_page_number }}">
          <span class="la la-long-arrow-right"></span></a>
        {% else %}
        <a class="next page-numbers disabled"><span class="la la-long-arrow-right"></span></a>
        {% endif %}
      </div>
    </nav>
  </div>
</div>
{% endif %}