biasharahub/biasharahub/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages.views import flatpage
from django.contrib.sitemaps.views import index, sitemap
from django.urls import path, include

from biasharahub.views import Home, NewsletterView
from business.sitemaps import BusinessSitemap
from reviews.sitemaps import ReviewSitemap

sitemaps = {
    'business': BusinessSitemap,
    'review': ReviewSitemap,

}
urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', Home.as_view(), name='home'),
                  path('newsletter', NewsletterView.as_view(), name='newsletter'),
                  path('accounts/', include('allauth.urls', )),
                  path('accounts/', include('accounts.urls', namespace='accounts')),
                  path('categories/', include('categories.urls', namespace='categories')),
                  path('business/', include('business.urls', namespace='business')),
                  path('reviews/', include('reviews.urls', namespace='reviews')),
                  path('comments/', include('comments.urls', namespace='comments')),
                  path('invitations/', include('invitations.urls', namespace='invitations')),
                  path('locations/', include('locations.urls', namespace='locations')),
                  path('opening-hours/', include('openinghours.urls', namespace='openinghours')),
                  path('about-us/', flatpage, {'url': '/about-us/'}, name='about'),
                  path('contact-us/', flatpage, {'url': '/contact-us/'}, name='contact'),
                  path('policy/', flatpage, {'url': '/policy/'}, name='policy'),

                  path('sitemap.xml', index, {'sitemaps': sitemaps}),
                  path('sitemap-<section>.xml', sitemap, {'sitemaps': sitemaps},
                       name='django.contrib.sitemaps.views.sitemap'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

biasharahub/locations/urls.py
from django.urls import path

from .views import LocationCreate, LocationDetail, LocationList, LocationUpdate

app_name = 'categories'

urlpatterns = [
    path('new/', LocationCreate.as_view(), name='new'),
    path('<slug:slug>/', LocationDetail.as_view(), name='detail'),
    path('<slug:slug>/edit/', LocationUpdate.as_view(), name='edit'),

    path('', LocationList.as_view(), name='list'),

]

biasharahub/reviews/urls.py
from django.urls import path

from favourites.views import vote_up, vote_down, ReviewVoteUp
from .views import ReviewList, ReviewDetail, ReviewCreate, ReviewEdit, photos

app_name = 'reviews'

urlpatterns = [
    path('', ReviewList.as_view(), name='list'),
    path('<slug:slug>/', ReviewDetail.as_view(), name='detail'),
    path('<slug:slug>/new/', ReviewCreate.as_view(), name='new'),
    path('<slug:slug>/edit/', ReviewEdit.as_view(), name='edit'),
    path('<slug:slug>/photos/', photos, name='photos'),
    path('<slug:slug>/review_like/', ReviewVoteUp.as_view(), name='review_like'),
    path('<slug:slug>/vote_up/', vote_up, name='vote_up'),
    path('<slug:slug>/vote_down/', vote_down, name='vote_down'),

]

biasharahub/locations/models.py
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse

from utility.models import Common


class Country(Common):
    website = models.URLField(blank=True, null=True)

    class Meta:
        verbose_name_plural = "countries"

    def get_absolute_url(self):
        return reverse("country:detail", kwargs={"slug": self.slug})


class Location(Common):
    icon = models.CharField(max_length=50, unique=True)
    country = models.ForeignKey(Country, related_name='country', on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "locations"
        ordering = ['name']

    def get_absolute_url(self):
        return reverse("locations:detail", kwargs={"slug": self.slug})

biasharahub/locations/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView, UpdateView
from django.views.generic.detail import SingleObjectMixin

from locations.models import Location


class LocationList(ListView):
    model = Location
    paginate_by = 12
    context_object_name = "location"
    template_name = 'locations/list.html'


class LocationDetail(SingleObjectMixin, ListView):  # this is equivalent to DetailView with Pagination
    model = Location
    context_object_name = "location"
    template_name = 'locations/detail.html'
    paginate_by = 15

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Location.objects.all())
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        return self.object.company.all()


class LocationCreate(LoginRequiredMixin, CreateView):
    model = Location
    fields = '__all__'
    template_name = 'includes/form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = " Add Location "
        return context


class LocationUpdate(LoginRequiredMixin, UpdateView):
    model = Location
    fields = '__all__'
    template_name = 'includes/form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = " Update Location "
        return context

biasharahub/templates/locations/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}  {{ location.name }}  | {{ block.super }} {% endblock %}

{% block bg-image-holder %}
<div class="bg_image_holder"><img alt="" src='{% static "img/breadcrumb1.jpg" %}'></div>
{% endblock %}

{% block page-title %}
<h1 class="page-title">{{ location.name }}</h1>
{% endblock %}

{% block breadcrumb_item %}
<li class="breadcrumb-item"><a href='{% url "locations:list" %}'><i class="fa fa-list"></i>List</a></li>
<li aria-current="page" class="breadcrumb-item active">{{ location.name }}</li>
<li class="breadcrumb-item"><a href='{% url "locations:edit" location.slug %}'><i class="fa fa-plus"></i>Edit</a></li>

{% endblock %}


{% block content %}
<section class="author-info-area section-padding-strict section-bg">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-md-7 m-bottom-30">
        <div class="atbd_author_module">
          <div class="atbd_content_module">
            <div class="atbd_content_module__tittle_area">
              <div class="atbd_area_title">
                <h4><span class="fa fa-location"></span>{{ location.name }}</h4>
              </div>
            </div>
            <div class="atbdb_content_module_contents">
              <p>{{ location.description }}</p>
            </div>
          </div>
        </div><!-- ends: .atbd_author_module -->
      </div><!-- ends: .col-md-8 -->
      <div class="col-lg-12">
        <div class="row">
          {% for business in page_obj %}
          <div class="col-lg-4 col-sm-6">
            <div class="atbd_single_listing ">
              <article class="atbd_single_listing_wrapper">
                <figure class="atbd_listing_thumbnail_area">
                  <div class="atbd_listing_image">
                    <a href="">
                      <img alt="listing image" src="img/p1.jpg">
                    </a>
                  </div><!-- ends: .atbd_listing_image -->
                  <div class="atbd_author atbd_author--thumb">
                    <a href="{{ business.get_absolute_url }}">
                      <img alt="Logo" class="center-cropped" src='{% if business.logo %}
                          {{ business.logo3.url }} {% else %} {% static "img/author-thumb2.jpg" %} {% endif %}'>
                      <span class="custom-tooltip">{{ business.name }}</span>
                    </a>
                  </div>
                  <div class="atbd_thumbnail_overlay_content">
                    <ul class="atbd_upper_badge">
                      {% if business.featured %}
                      <li><span class="atbd_badge atbd_badge_featured">Featured</span></li>
                      {% endif %}
                      {% if business.verified %}
                      <li><span class="atbd_badge atbd_badge_popular">Verified</span></li>
                      {% endif %}
                    </ul><!-- ends .atbd_upper_badge -->
                  </div><!-- ends: .atbd_thumbnail_overlay_content -->
                </figure><!-- ends: .atbd_listing_thumbnail_area -->
                <div class="atbd_listing_info">
                  <div class="atbd_content_upper">
                    <h4 class="atbd_listing_title">
                      <a href="">{{ business.name }}</a>
                    </h4>
                    <div class="atbd_listing_meta">
                      <span class="atbd_meta atbd_listing_rating">{{ business.average_rating | floatformat }}
                        <i class="la la-star"></i></span>
                      <span class="atbd_meta atbd_listing_price">$55.00</span>
                      <span class="atbd_meta atbd_badge_open">Open Now</span>
                    </div><!-- End atbd listing meta -->
                    <div class="atbd_listing_data_list">
                      <ul>
                        <li>
                          <p><span class="la la-map-marker"></span>{{ business.address }},
                            {{ business.location }}, {{ business.location.country }}</p>
                        </li>
                        <li>
                          <p><span class="la la-phone"></span>(+254) {{ business.phone }}</p>
                        </li>
                        <li>
                          <p><span class="la la-calendar-check-o"></span>
                            Posted {{ business.publish|timesince }} ago</p>
                        </li>
                      </ul>
                    </div><!-- End atbd listing meta -->
                  </div><!-- end .atbd_content_upper -->
                  <div class="atbd_listing_bottom_content">
                    <div class="atbd_content_left">
                      <div class="atbd_listing_category">
                        <a href=""><span class="la la-glass"></span>{{ business.category }}</a>
                      </div>
                    </div>
                    <ul class="atbd_content_right">
                      <li class="atbd_count"><span class="la la-eye"></span>900+</li>
                      <li class="atbd_save">
                        <span class="la la-heart-o"></span>
                      </li>
                    </ul>
                  </div><!-- end .atbd_listing_bottom_content -->
                </div><!-- ends: .atbd_listing_info -->
              </article><!-- atbd_single_listing_wrapper -->
            </div>
          </div><!-- ends: .col-md-6 -->
          {% endfor %}
        </div>
        {% include 'includes/pagination.html' %}
      </div><!-- ends: .col-lg-12 -->
    </div>
  </div>
</section><!-- ends: .author-info-area -->
{% endblock content %}

biasharahub/templates/locations/list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}  Locations  | {{ block.super }} {% endblock %}

{% block bg-image-holder %}
<div class="bg_image_holder"><img alt="" src='{% static "img/breadcrumb1.jpg" %}'></div>
{% endblock %}

{% block page-title %}
<h1 class="page-title">All Locations</h1>
{% endblock %}

{% block breadcrumb_item %}
<li class="breadcrumb-item"><a href='{% url "locations:new" %}'><i class="fa fa-plus"></i>New</a></li>
<li aria-current="page" class="breadcrumb-item active">All Locations</li>
{% endblock %}

{% block content %}

<section class="section-padding-strict section-bg">
  <div class="atbd_location_grid_wrap">
    <div class="container">
      <div class="row">
        {% for location in location %}
        <div class="col-lg-3 col-md-4 col-sm-6">
          <a class="atbd_location_grid" href="{{ location.get_absolute_url }}">
            {{ location.name }} ({{ location.company.count }})
          </a>
        </div><!-- ends: .col-lg-3 -->
        {% endfor %}
      </div>
    </div>
  </div><!-- ends: .atbd_location_grid_wrap -->
</section><!-- ends: section -->
<!-- ends: section -->


{% endblock %}